### - Teste de Rotas Backend

GET http://localhost:3000/altura
Content-Type: application/json

### - Teste do nome
GET http://localhost:3000/nome
Content-Type: application/json

### - Teste de Cadastro
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Ana",
    "idade": 15,
    "altura": 1.78,
    "peso": 55
}

### - Teste de Cadastro do usuário
POST http://localhost:3000/usuario2
Content-Type: application/json

{
    "nome": "Ana",
    "email": "ana@gmail.com",
    "senha": "abc"
}
